server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# Check the service at the specific Port of the server
# http://192.168.56.1:8081/location
