server:
  port: 8084

spring:
  application:
    name: doctor-portal

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #  Not iscoverable as it is a client that consumes from server
    register-with-eureka: false
